export const COMPANIES = [
  {
    title: "Claro Pay",
    image: "claro",
    color: "#D23D38",
    home: "https://claropay.com.ar",
    tna: 68.52,
    tnaPage: null,
  },
  {
    title: "MercadoPago",
    image: "mercadopago",
    color: "#05B9FF",
    home: "https://www.mercadopago.com.ar",
    tna: 69.69,
    tnaPage: "https://calculadora-mercadopago.com.ar/ganancias",
  },
  {
    title: "NaranjaX",
    image: "naranja",
    color: "#E85212",
    home: "https://www.naranjax.com/",
    tna: 78,
    tnaPage:
      "https://blog.naranjax.com/proba-la-calculadora-tna-para-ver-cuanto-podes-ganar-con-naranja-x/",
  },
  {
    title: "Personal",
    image: "personal",
    color: "#5A56FA",
    home: "https://www.personalpay.com.ar/cuentas-remuneradas",
    tna: 72,
    tnaPage: null,
  },
  {
    title: "Prex",
    image: "prex",
    color: "#4D2597",
    home: "https://www.prexcard.com.ar/cuenta-remunerada",
    tna: 73.18,
    tnaPage: null,
  },
  {
    title: "Supervielle",
    image: "supervielle",
    color: "#DE0409",
    home: "https://www.supervielle.com.ar/",
    tna: 71.11,
    tnaPage: null,
  },
  {
    title: "Uala",
    image: "uala",
    color: "#D65A71",
    home: "https://www.uala.com.ar/",
    tna: 68.4,
    tnaPage: null,
  },
  {
    title: "n1u",
    image: "n1u",
    color: "#FF009D",
    home: "https://n1u.app/",
    tna: 71.03,
    tnaPage: null,
  },
  {
    title: "Taca Taca",
    image: "tacataca",
    color: "#02D5B5",
    home: "https://www.taca-taca.com.ar/",
    tna: 68.61,
    tnaPage: null,
  },
  {
    title: "Banco Galicia",
    image: "galicia",
    color: "#FA6400",
    home: "https://www.galicia.ar/personas",
    tna: 69.2,
    tnaPage: null,
  },
  {
    title: "AstroPay",
    image: "astropay",
    color: "#27DEAF",
    home: "https://astropay.com/",
    tna: 65.1,
    tnaPage: null,
  },
].sort((a, b) => b.tna - a.tna);
